/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

char global[255];
int size;

void *DecToHexStr(int dec, char *str)
{ sprintf(str, "%X", dec); }

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
    char *message_hex;
	static wyjscie  result;
    int dec;
    dec = argp->buff;
    
    DecToHexStr(dec, message_hex);
	
    size = strlen(message_hex);
    
    for(int i=0; i<size; i++)
    {
        global[i] = message_hex[i];
    }
    
    printf("Twoja zaszyfrowana wiadomosc: %s\n", global);

	return &result;
}

wyjscie2 *
obliczenia2_1_svc(wejscie2 *argp, struct svc_req *rqstp)
{
	static wyjscie2  result2;
    
    printf("przekazuje wiadomosc\n");
    
    for(int i=0; i<size; i++)
    {
        result2.buffer[i] = global[i];
    }


	return &result2;
}
