/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "app.h"

bool_t
xdr_wejscie (XDR *xdrs, wejscie *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->buff))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wyjscie (XDR *xdrs, wyjscie *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wejscie2 (XDR *xdrs, wejscie2 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->buff))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wyjscie2 (XDR *xdrs, wyjscie2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
